// src/theme/themeColors.ts

export const themeColors = {
    light: {
      background: "#ECEFF4",
      backgroundprofile: '#b2dfdb',
      card: "#fff",
      text: "#222",
      searchBar: "#fff",
      border: "#ccc",
      placeholder: "#888",
      categoryBg: "#fff",
      iconColor: '#888',
      trashcan: 'red',
      checkmark: '#4CAF50',
      checkmarkmusic: '#3F51B5',
      checkmarkTutor: '#FF9800',
      categoryText: "#0097a7",
      categoryBorder: "#007aff",
      primary: "#007AFF",
      muted: "#999",
      textSecondary: "#666",
      shadow: "#000",
    },
    dark: {
      background: "#191c1f",
      backgroundprofile: '#191c1f',
      card: "#22272e",
      text: "#fff",
      searchBar: "#22272e",
      border: "#2c2f35",
      iconColor: '#fff',
      placeholder: "#fff",
      trashcan: '#fff',
      checkmark: '#fff',
      checkmarkmusic: '#fff',
      checkmarkTutor: '#fff',
      categoryBg: "#23272f",
      categoryText: "#fff",
      categoryBorder: "#fff",
      primary: "#1976D2",
      success: "#388E3C",
      pending: "#555",
      pendingText: "#DDD",
      avatarBg: "#222B36",
      avatarText: "#EEE",
      shadow: "#000",
      muted: "#BBB",
      textSecondary: "#A0A0A0",
    },
  };
  