const cities = [
    { city: "Ancon", region: "Lima"},
    { city: "Ciudad Pachacutec", region: "Lima"},
    { city: "San Juan de Lurigancho", region: "Lima" },
    { city: "Puente Piedra", region: "Lima" },
    { city: "San Martin de Porres", region: "Lima" },
    // { city: "Comas", region: "Provincia de Lima" },
    { city: "Villa el Salvador", region: "Lima" },
    { city: "Rimac", region: "Lima" },
    { city: "Los Olivos", region: "Provincia de Lima" },
    { city: "Lima", region: "Provincia de Lima" },
    // { city: "Independencia", region: "Lima" },
    { city: "Surquillo", region: "Lima" },
    { city: "Chorrillos", region: "Lima" },
    { city: "Santiago de Surco", region: "Lima" },
    { city: "San Isidro", region: "Lima" },
    { city: "Miraflores", region: "Lima" },
    // { city: "La Victoria", region: "Lima" },
    { city: "Callao", region: "Callao" },
    { city: "Bellavista", region: "Callao" },
    // { city: "Carmen de la Legua Reynoso", region: "Callao" },
    { city: "La Perla", region: "Callao" },
    // { city: "La Punta", region: "Callao" },
    { city: "Mi Peru", region: "Callao" },
    { city: "Ventanilla", region: "Callao" },
    { city: "San Miguel", region: "Lima" },
    { city: "Jesus Maria", region: "Lima" },
    { city: "Magdalena del Mar", region: "Lima"},
    { city: "La Molina", region: "Lima" },
    { city: "San Borja", region: "Lima"},
    { city: "Barranco", region: "Lima"},
    { city: "Carabayllo", region: "Lima"}
];

export default cities;